### ISSUE TITLE
Modification de la structure

### ISSUE THREAD

**Issue by gtraxx** [sire-sam/sireSam_css#1]
Tu peux modifier la structure des dossiers comme ceci :
- src
  - base.css
  - position.css
- index.html (pour peut être des exemples)
- GPL-LICENCE.txt
- LICENCE

ce n'est qu'une proposition suite au travail déjà fait dans SC

**Comment by gtraxx** [comment]
tu peux placer un fichier index.html avec un exemple d'utilisation :
- Entête
- Navigation
- Contenu
- Footer

**Comment by sire-sam** [comment]
La structure à été modifiée.
Pour le fichier html de test c'est encore un brouillon avec des 'notes' personnels ( ;) )
