### ISSUE TITLE
List/ navigation

### ISSUE THREAD

**Issue by sire-sam** [sire-sam/sireSam_css#5]
Il serait Utile d'intégrer rapidement les feuilles liées à la gestion de liste!

Au moins les navigations horizontale et verticales!

**Comment by gtraxx** [comment]
Ce sera plus facile de créer les navigations avec les feuilles de gestions

**Comment by gtraxx** [comment]
Saura tu envoyé la feuille pour les listes et navigations, je vais en avoir besoin :)

**Comment by sire-sam** [comment]
Faut que je nettoie la feuille existante, elle n'est pas utilisable en l'état

**Comment by gtraxx** [comment]
ok je vais attendre la feuille, j'ai mis à jour les autres avec tes modifications, mais j'ai écraser la modification que j'avais fais pour le submit avec inline-block.
Pour ne plus écraser ou modifier tes fichiers, je place tout dans style.css y compris une ligne pour écraser une partie du style du submit.

``` css
input[type="submit"]{
    display: inline-block;
}
```

**Comment by sire-sam** [comment]
Je viens d'ajouter la feuille list.css.

Elle comprend la majorité des cas de navigation. 
La plus part des class on été testée, excepté la classe pagination.
Je n'ai encore rien tester dans IE7, il y à deux trois déclarations pour lesquels j'ai des doutes.

Les class présentent ne s'utilisent que sur la balise <ul> principale contenant la navigation (même si navigation multi niveaux)

.h-nav => liste horizontal en flottant
.v-nav => Liste vertical avec sous-navigation dans le flux
.v-nav.expandable => liste vertical avec sous-navigation en positionnement absolut (à droite)
.v-nav.js-expandable => liste vertical avec sous-navifation dans le flux, mais affichage sur évènement JS (jquerry.treeview)
.breadcrumb => fil d'ariane
.pagination => simple pagination
